name: Docker compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compose container
        run: docker compose build
